### ISSUE TITLE
Compile errors: parseOutput / printOutput functions missing

### ISSUE THREAD

**Issue by bjornleffler** [AaronSaikovski/gogoodwe#11]
With golang 1.23, I run the following commands:

git clone https://github.com/AaronSaikovski/gogoodwe
cd gogoodwe
make build

Which results in the following output:

go build -o bin/gogoodwe ./cmd/gogoodwe/main.go
github.com/AaronSaikovski/gogoodwe/cmd/gogoodwe/powerstation
cmd/gogoodwe/powerstation/monitordetails.go:90:17: undefined: parseOutput
cmd/gogoodwe/powerstation/monitordetails.go:94:2: undefined: printOutput
cmd/gogoodwe/powerstation/monitordetails.go:112:17: undefined: parseOutput
cmd/gogoodwe/powerstation/monitordetails.go:116:2: undefined: printOutput
make: *** [Makefile:37: build] Error 1

Looks like there might be a missing file in the cmd/gogoodwe/powerstation directory?

**Comment by AaronSaikovski** [comment]
Thanks for reporting this and iI could reproduce this easily. I will fix this ASAP.

**Comment by bjornleffler** [comment]
Thanks for the quick reply!

**Comment by AaronSaikovski** [comment]
no worries :-)

**Comment by AaronSaikovski** [comment]
fixed in v2.0.2

**Comment by AaronSaikovski** [comment]
fixed in v2.0.2
