### ISSUE TITLE
cannot unmarshal number

### ISSUE THREAD

**Issue by wobeyer** [AaronSaikovski/gogoodwe#8]
I use go version 1.21.3 linux/arm. On starting gogoodwin I get
json: cannot unmarshal number 1697453970355 into Go struct field .data.timestamp of type int

**Comment by AaronSaikovski** [comment]
ok I will check into this...thanks for reporting

**Comment by AaronSaikovski** [comment]
Fixed in v1.4.3

**Comment by AaronSaikovski** [comment]
https://github.com/AaronSaikovski/gogoodwe/releases/tag/v1.4.3
